### ISSUE TITLE
Gitignore the .idea folder

### ISSUE THREAD

**Issue by LeeBergstrand** [LavenderGoons/TheDanMan#1]
The .idea folder contains xml files to set up the dev environment. You may want to .gitignore some of them or the entire .idea directory.

http://stackoverflow.com/questions/11968531/what-to-gitignore-from-the-idea-folder

**Comment by LavenderGoons** [comment]
Ok I will look into that. Thanks

**Comment by LavenderGoons** [comment]
The idea folder has been removed
